[package]
name = "ps-organizer"
version = "1.1.0"
edition = "2024"
description = "A command-line tool to organize PS source files."
license = "MIT"

[dependencies]
clap = { version = "4", features = ["derive"] }
walkdir = "2"
anyhow = "1"

[dev-dependencies]
tempfile = "3"
